stages:
  - build
  - validate

before_script:
  - ruby -v
  - which ruby

.ios-build: &ios-build
  tags:
    - iOS
    - Xcode9.3

'Branch Build':
  <<: *ios-build
  script:
    - fastlane test --verbose

'Master Build':
  <<: *ios-build
  script:
    - fastlane test --verbose

'Validate Podspec Version Optional':
  <<: *ios-build
  stage: test
  allow_failure: true
  except: master
  script: ./validate_version.sh

'Lint Podspec Optional':
  <<: *ios-build
  stage: test
  allow_failure: true
  except: master
  script: pod spec lint TeamSnapSDK.podspec

'Validate Podspec Version Required':
  <<: *ios-build
  stage: test
  only: master
  script: ./validate_version.sh

'Lint Podspec Required':
  <<: *ios-build
  stage: test
  only: master
  script: pod spec lint TeamSnapSDK.podspec
